// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptFile(arg1, arg2) {
  return window['go']['main']['App']['DecryptFile'](arg1, arg2);
}

export function EncryptFile(arg1, arg2) {
  return window['go']['main']['App']['EncryptFile'](arg1, arg2);
}

export function GetFilePath() {
  return window['go']['main']['App']['GetFilePath']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
