// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptFile(arg1:string,arg2:string):Promise<string>;

export function EncryptFile(arg1:string,arg2:string):Promise<string>;

export function GetFilePath():Promise<string>;

export function Greet(arg1:string):Promise<string>;
